### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by jamiebyer** [jamiebyer/climate-maunaloa-v2#1]
- [x] User can select which of the available data sets to display (checkboxes)
- [x] User can select "all" or "single month each year" (13-item dropdown: all, Jan, Feb, etc.)
- [x] User can adjust time-scale (x-axis start & end)
- [ ] User can adjust one straight line slope and offset (we don't need two)
- [ ] Can we make the straight line visible regardless of x-axis limits?
- [x] Also plot (separate y-axis) the Northern Hemisphere mean monthly surface temperature
- [x] Introduction/instructions, etc. read in from md file
- [x] Comment out the survey for now

**Comment by fhmjones** [comment]
**Requested changes:** (Jan 10th, 2022). Everything was much liked, and discussion resulted in the following ideas:
- [x] Temperature data no longer needed. It was an idea worth checking out - but Tara decided it was "distracting" from the main objectives for this app. 
- [x] Drop the "plot segments" buttons.
- [x] Change "Signal Type" to "Data Source", and keep only the raw data. Then add same type of raw CO2 data from the South Pole. These are available at the same location, in the same format (many more NaN's in early years). See https://scrippsco2.ucsd.edu/data/atmospheric_co2/spo.html . Result will be just two checkboxes, one for raw Mauna Loa data and one for raw South Pole data. 
- [x] Can the month dropbox permit more than one selection (eg to compare, March and October)? If not, months (and "all") will have to be check boxes, unless you have another good idea. 
- [x] Allow all default graph options (Plotly's upper-right icons) to appear.  
- [x] Reorganize: Show instructions, then just the plotting options for the graph. Then we'll put the line-fitting features below the graph. That could include a second set of instructions (via MD file), the slider controls, and the prediction result. Therefore, the graph title can be changed to something fixed, with predicted temperature given as a line of text below the line-making controls. 
- [ ] I will generate two new instructions files and send them to you - one for the beginning and a shorter one for the manual straight line fitting part. 
- [x] Change wording: Linear "fit" is not really a "fit", so lets call it a manual straight line approximation. 
- [x] lower priority: Can the prediction result be generated for a user specified year? That means entering a year value constrained to between 1960 and 2030. I imagine asking students to consider a specific x-range span, manually fit a straight line to data in that range, then having the app provide a prediction from that line for the chosen year.
